use_frameworks!

target 'JXView_Example' do
  pod 'JXView', :path => '../'

  target 'JXView_Tests' do
    inherit! :search_paths

  pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 7.1.2'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
